# Project Mu GitHub Issue Configuration File
#
# NOTE: This file is automatically synchronized from Mu DevOps. Update the original file there
#       instead of the file in this repo.
#
# - Mu DevOps Repo: https://github.com/microsoft/mu_devops
# - File Sync Settings: https://github.com/microsoft/mu_devops/blob/main/.sync/Files.yml
#
# Copyright (c) Microsoft Corporation.
# SPDX-License-Identifier: BSD-2-Clause-Patent
#

contact_links:
<<<<<<< HEAD
  - name: Reporting Security Issues
    url: https://www.tianocore.org/tianocore-wiki.github.io/security/processes/reporting_security_issues.html
    about: Read the wiki page that describes the process here
  - name: EDK II Development Mailing List
    url: https://edk2.groups.io/g/devel
    about: Ask questions on the mailing list (devel@edk2.groups.io)
  - name: EDK II Discussions
    url: https://github.com/tianocore/edk2/discussions
    about: You can also reach out on the Discussion section of this repository
=======
  - name: 📃 Project Mu Documentation
    url: https://microsoft.github.io/mu/
    about: Goals, principles, repo layout, build instructions, and more.
>>>>>>> d4d2ac9173 (BaseCore: Enable CI)
